---
# Database
spring:
  datasource:
    url: jdbc:postgresql://${COMMENT_DB}:5432/${COMMENT_DB_NAME}
    password: ${COMMENT_DB_PW}
    username: ${COMMENT_DB_USER}
  # kafka servers
  kafka:
    bootstrap-servers: kafka:9092
# Keycloak
keycloak:
  auth-server-url: http://localhost:8090/auth/
  proxy-url: http://keycloak:8080/auth/

# CORS
security:
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-methods: '*'
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/
server:
  servlet:
    session:
      cookie:
        domain: localhost
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto